import { Bot } from '@lib/bot';
import { CommandInteraction, SlashCommandBuilder } from 'discord.js';


export const command = new SlashCommandBuilder()
	.setName('ping')
	.setDescription('Pong !');


/**
 * Command's handler.
 * @param inter The interaction generated by the command.
 * @param client The bot's client.
 */
export async function execute(inter: CommandInteraction, client: Bot) {
	await inter.reply(`Pong ${inter.user} !`).catch();
}
